### ISSUE TITLE
Remove regional (us-west-2) hardcoding from values.yaml and other manifests

### ISSUE THREAD

**Issue by Hashfyre** [infracloudio/sre-stack#37]

**Comment by saurabh3460** [comment]
Common .env file at root of the project can be useful since makfile and bash can take it as source using `include` and `source` respectively.

.env file will contain:

```.env
CLUSTER_NAME=sre-stack
AWS_REGION=us-west-2
RMQ_CLUSTER_NS=robot-shop
LOAD_NS=pending-orders
NODE_GROUP=loadgen-ng
SCENARIO_TIMEOUT=5m
WAIT_TIMEOUT=5m
MAX_NODE=8
```

At last we will have values.yaml across the project which can be override using `--set` flag e.g `--set mysql_host=<url>` and we can set this while installing helm using makefile.

**Comment by saurabh3460** [comment]
#44
